language: r
sudo: required
dist: trusty
cache:
  - packages
  - ccache

services:
  - docker

pandoc_version: 1.17.2



addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libv8-3.14-dev
      - libarchive-dev
      - proj-bin
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
      - libnetcdf-dev
      - netcdf-bin
      - gdal-bin
      - libssl-dev
      - libgl1-mesa-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - ccache	  

before_install:
  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  #- sudo apt-get -f install liblwgeom-dev libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler
  #- sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libhdf4-alt-dev
  ## NetCDF and geo-spatial wunderkind
  # - sudo apt-get install libv8-3.14-dev libarchive-dev libnetcdf-dev proj-bin  libproj-dev libgdal-dev gdal-bin libgeos-dev  libssl-dev libgl1-mesa-dev libglu1-mesa-dev libudunits2-dev libprotobuf-dev protobuf-compiler --assume-yes
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2' --no-document
  - gem install octokit
  # see blogpost https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
  # mkdir
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  
r_github_packages:
 - brendan-r/brocks
 - tidyverse/rlang
 - tidyverse/ggplot2
 - yihui/tinytex
 - rspatial/dismo
 
#r_packages:
#  - sp
#  - rgdal
#  - rgeos
#  - raster
#  - sf
#  - geosphere
#  - dismo
#  - leaflet
#  - unmarked
#  - AHMbook
#  - dismo
#  - maptools
#  - ks
#  - webshot
#  - dplyr
#  - maps
#  - tidyverse
#  - lwgeom
#  - gdalUtils
#  - gstat
#  - spatstat
#  - velox
  

branches:
  only: develop
  
script:
  - Rscript -e 'servr:::knit_maybe(input = c(".", "_pages","website"), output = c(".","_pages","website"), "build.R", "jekyll")'
#  - Rscript -e 'servr:::knit_maybe(input = c("."), output = c("."), "build.R", "jekyll")' 
deploy:
  provider: pages
  edge:
    branch: v1.10.11
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_PATH
  on:
    branch: develop
  target_branch: master