language: r
cache: packages
pandoc_version: 1.17.2

branches:
  only: develop

script:
  - Rscript -e 'servr:::knit_maybe(c(".", "_pages", "_pages"), c(".", "_pages", "_pages"), "build.R", "jekyll")'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: develop
  target_branch: master