sudo: required

services:
  - docker

language: r
cache:
  packages: true
pandoc_version: 1.17.2
r_github_packages:
  - brendan-r/brocks
  - tidyverse/rlang
  - tidyverse/ggplot2
r_packages:
  - sp
  - rgdal
  - rgeos
  - raster
  - sf
  - geosphere
  - dismo
  - leaflet
  - unmarked
  - AHMbook
  - dismo
  - maptools
  - ks
  - webshot
  - dplyr
  - maps
  - tidyverse
  - lwgeom
  - gdalUtils
  
before_install:
  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  #- sudo apt-get -f install liblwgeom-dev libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler
  #- sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libhdf4-alt-dev
  ## NetCDF and geo-spatial wunderkind
  - sudo apt-get install libv8-3.14-dev libarchive-dev libnetcdf-dev proj-bin  libproj-dev libgdal-dev gdal-bin libgeos-dev  libssl-dev libgl1-mesa-dev libglu1-mesa-dev libudunits2-dev libprotobuf-dev protobuf-compiler --assume-yes
  
branches:
  only: develop
  
script:
  - Rscript -e 'servr:::knit_maybe(c(".", "_pages", "_pages"), c(".", "_pages", "_pages"), "build.R", "jekyll")'
  
deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  github_token: $GITHUB_PATH
  on:
    branch: develop
  target_branch: master