title: "M.T.Hallworth"
lsi:
    highlighter:  rouge
    permalink:   date
    name: Michael T. Hallworth
    description: mhallwor.github.io
    url: http://mhallwor.github.io
theme: jekyll-theme-cayman